module.exports = {
	signUp: require('./signUp'),
	logIn: require('./logIn'),
	clients: require('./clients'),
	members: require('./members'),
	tasks: require('./tasks'),
	tickets: require('./tickets'),
	leads: require('./leads'),
	sales: require('./sales'),
	quotations: require('./quotations'),
	invoices: require('./invoices'),
	payments: require('./payments'),
	packages: require('./packages'),
	utils: require('./utils'),
	accounts: require('./accounts'),
	dashboard: require('./dashboard'),
	hearingDates: require('./hearingDates'),
	notifications: require('./notifications'),
	calendar: require('./calendar'),
}