name: Prod CD

on:
  push:
    branches:
      - main

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    steps:

    # - name: curl
    #   uses: wei/curl@master
    #   with:
    #     args: https://5f5d-183-82-155-131.ngrok.io/${{ secrets.TMS_USER }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TMS_HOST }}
        username: ${{ secrets.TMS_USER }}
        key: ${{ secrets.TMS_EC2_KEY }}
        port: ${{ secrets.TMS_SSH_PORT }}
        script: |
          source ~/.zshrc 
          cd ~/TMSBackend/ 
          pm2 restart tms --update-env 
          sleep 3
          pm2 log tms --nostream